# Generated by Django 5.1.2 on 2024-11-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.IntegerField()),
                ("project_name", models.CharField(max_length=100)),
                ("project_description", models.TextField()),
                ("project_url", models.URLField()),
                ("project_image", models.URLField()),
                ("project_type", models.CharField(max_length=100)),
                ("project_status", models.CharField(max_length=100)),
                ("project_owner", models.CharField(max_length=100)),
                ("project_owner_email", models.EmailField(max_length=254)),
                ("project_cost_m2", models.FloatField()),
            ],
        ),
    ]
