# Generated by Django 5.1.2 on 2024-11-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IntDesign", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact", models.IntegerField()),
                ("contact_name", models.CharField(max_length=100)),
                ("contact_phone", models.IntegerField()),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_message", models.TextField()),
            ],
        ),
    ]
